apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-hello.fullname" . }}-env
  labels:
{{ include "flask-hello.labels" . | indent 4 }}
data:
  POSTGRES_HOST: {{ template "postgresql.hostname" . }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | quote }}
  POSTGRES_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresql.postgresqlUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | quote }}

  REDIS_HOST: {{ template "redis.hostname" . }}
  ELASTICSEARCH_HOST: {{ template "elasticsearch.hostname" . }}

  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: {{ .Values.service.port | quote }}
  FLASK_DEBUG: "true"

  ZMQ_ROUTER_PORT: {{ .Values.zmq.router_port | quote }}
  ZMQ_DEALER_PORT: {{ .Values.zmq.dealer_port | quote }}
  ZMQ_ROUTER_HOST: {{ include "flask-hello.device.hostname" . | quote }}
  ZMQ_DEALER_HOST: {{ include "flask-hello.device.hostname" . | quote }}
  ZMQ_PUBLISHER_PORT: {{ .Values.zmq.publisher_port | quote }}
  ZMQ_SUBSCRIBER_PORT: {{ .Values.zmq.subscriber_port | quote }}
  ZMQ_PUBLISHER_HOST: {{ include "flask-hello.device.hostname" . | quote }}
  ZMQ_SUBSCRIBER_HOST: {{ include "flask-hello.device.hostname" . | quote }}
