{{- if .Values.zmq.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "flask-hello.fullname" . }}-cron
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            name: {{ .Chart.Name }}
            command: ['flask-hello', 'enqueue', '{{ .Chart.Name }}']
            envFrom:
              - configMapRef:
                  name: {{ include "flask-hello.fullname" . }}-env
          restartPolicy: OnFailure
{{- end }}
