# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: hello
# spec:
#   schedule: "* * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#             imagePullPolicy: {{ .Values.image.pullPolicy }}
#             name: {{ .Chart.Name }}
#             command: ['/venv/bin/flask-hello', 'web', '--debug', '--host=0.0.0.0', '--port=5000']
#             envFrom:
#               - configMapRef:
#                   name: {{ include "flask-hello.fullname" . }}-env
#           restartPolicy: OnFailure
