apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flask-hello.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: gabrielfalcao/flask-hello
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
        - name: POSTGRES_HOST
          value: {{ include "postgresql.fullname" . }}.default.svc.cluster.local
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_DATABASE
          value: {{ .Values.postgresql.database }}
        - name: POSTGRES_USERNAME
          value: {{ .Values.postgresql.username }}
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.password }}"
        ports:
        - containerPort: 5000
          name: api
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-hello
stringData:
  password: bar
  username: flask-hello
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-hello.fullname" . }}
  labels:
{{ include "flask-hello.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flask-hello.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
