---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "flask-hello.labels" . | indent 8 }}
    spec:
      initContainers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-check-installation
        command: ['/venv/bin/flask-hello', 'check']
        envFrom:
          - configMapRef:
              name: {{ include "flask-hello.fullname" . }}-env

      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-check-db-connection
        command: ['/venv/bin/flask-hello', 'check-db']
        envFrom:
          - configMapRef:
              name: {{ include "flask-hello.fullname" . }}-env

      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-db-migrate
        command: ['/venv/bin/flask-hello', 'migrate-db']
        envFrom:
          - configMapRef:
              name: {{ include "flask-hello.fullname" . }}-env
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "flask-hello.fullname" . }}-secrets
              key: postgresql-password

      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        command: ['/venv/bin/flask-hello', 'web']
        envFrom:
          - configMapRef:
              name: {{ include "flask-hello.fullname" . }}-env


        ports:
        - containerPort: 5000
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-hello.fullname" . }}
  labels:
{{ include "flask-hello.labels" . | indent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flask-hello.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "flask-hello.fullname" . }}-secrets
  labels:
{{ include "flask-hello.labels" . | indent 4 }}
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
