{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "flask-hello.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: m8.visualcu.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "flask-hello.fullname" . }}
          servicePort: 5000
  - host: visualcu.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "flask-hello.fullname" . }}
          servicePort: 5000
  - host: m3.visualcu.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "flask-hello.fullname" . }}
          servicePort: 5000
{{- end }}
