{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "flask-hello.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - wavemanda.la
    secretName: wavemandala-roots

  rules:
  - host: wavemanda.la
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "flask-hello.fullname" . }}
          servicePort: 5000
{{- end }}
