# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: {{ include "flask-hello.fullname" . }}-zeromq
# spec:
#   template:
#     spec:
#       containers:
#       - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#         imagePullPolicy: {{ .Values.image.pullPolicy }}
#         name: {{ .Chart.Name }}-zeromq-connection
#         command: ['/venv/bin/flask-hello', 'enqueue', 'hello-world']
#         envFrom:
#           - configMapRef:
#               name: {{ include "flask-hello.fullname" . }}-env

#       restartPolicy: Never
#   backoffLimit: 4
