---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}-kibana
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}-kibana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flask-hello.name" . }}-kibana
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        command: ['/venv/bin/flask-hello', 'kibana']
        env:
        - name: ELASTICSEARCH_HOSTS
          value: {{ template "elasticsearch.hostname" . }}

        ports:
        - containerPort: {{ .Values.kibana.service.port }}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-hello.fullname" . }}-kibana
  labels:
    app.kubernetes.io/name: {{ include "flask-hello.name" . }}-kibana
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      protocol: TCP
      name: kibana
  selector:
    app.kubernetes.io/name: {{ include "flask-hello.name" . }}-kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
