{{- if .Values.ngrok.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}-ngrok-tunnel
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}-ngrok-tunnel
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flask-hello.name" . }}-ngrok-tunnel
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
      - image: "{{ .Values.ngrok.image.repository }}:{{ .Values.ngrok.image.tag }}"
        imagePullPolicy: {{ .Values.ngrok.image.pullPolicy }}
        name: {{ .Chart.Name }}
        command:
          - http
          - '--authtoken'
          - {{ .Values.ngrok.token | quote }}
          - '--subdomain'
          - {{ .Values.ngrok.subdomain | quote }}
          - '--bindtls=true'
          - '--log=stderr'
          - {{ include "flask-hello.web.fqdn" . | quote }}

{{- end }}
