{{- if .Values.ngrok.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}-ngrok-tunnel
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}-ngrok-tunnel
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flask-hello.name" . }}-ngrok-tunnel
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
      - image: "{{ .Values.ngrok.image.repository }}:{{ .Values.ngrok.image.tag }}"
        imagePullPolicy: {{ .Values.ngrok.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
          - name: NGROK_AUTH
            valueFrom:
              secretKeyRef:
                name: {{ include "flask-hello.fullname" . }}-secrets
                key: ngrok-token

          - name: NGROK_SUBDOMAIN
            value: {{ .Values.ngrok.subdomain | quote }}

          - name: NGROK_DEBUG
            value: "true"

          - name: NGROK_BINDTLS
            value: "true"

          # due to a problem with the ngrok image the hostname:port
          # needs be provided here
          - name: NGROK_PORT
            value: {{ include "flask-hello.web.fqdn" . | quote }}

{{- end }}
