---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "flask-hello.fullname" . }}-secrets
  labels:
{{ include "flask-hello.labels" . | indent 4 }}
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  ngrok-token: {{ .Values.ngrok.token | b64enc | quote }}
