---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}-device
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-hello.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "flask-hello.labels" . | indent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        command: ['/venv/bin/flask-hello', 'device']
        envFrom:
          - configMapRef:
              name: {{ include "flask-hello.fullname" . }}-env

        ports:
        - containerPort: {{ .Values.zmq.router_port }}
          name: router
        - containerPort: {{ .Values.zmq.dealer_port }}
          name: dealer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flask-hello.device.service" . }}
  labels:
{{ include "flask-hello.labels" . | indent 4 }}

spec:
  type: Clu
  ports:

    - port: {{ .Values.zmq.router_port }}
      targetPort: {{ .Values.zmq.router_port }}
      protocol: TCP
      name: router
    - port: {{ .Values.zmq.dealer_port }}
      targetPort: {{ .Values.zmq.dealer_port }}
      protocol: TCP
      name: dealer
  selector:
    app.kubernetes.io/name: {{ include "flask-hello.name" . }}-device
    app.kubernetes.io/instance: {{ .Release.Name }}
