name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile*') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build base docker image
      uses: whoan/docker-build-with-cache-action@v3
      with:
        username: gabrielfalcao
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: gabrielfalcao/flask-hello-base
        image_tag: "${{ github.sha }}"
        dockefile: Dockerfile.base

    - name: Build docker image for kubernetes
      uses: whoan/docker-build-with-cache-action@v3
      with:
        username: gabrielfalcao
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: gabrielfalcao/k8s-flask-hello
        image_tag: "${{ github.sha }}"
        dockefile: Dockerfile
