name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request: {}



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and push base Docker image using cache
      uses: whoan/docker-build-with-cache-action@v3
      with:
        username: gabrielfalcao
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: gabrielfalcao/flask-hello-base
        image_tag: "${{ github.sha }}"
        dockefile: Dockerfile.base

    - name: Build and push Docker image for Kubernetes using cache
      uses: whoan/docker-build-with-cache-action@v3
      with:
        username: gabrielfalcao
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: gabrielfalcao/k8s-flask-hello
        image_tag: "${{ github.sha }}"
        dockefile: Dockerfile
